# Generated by Django 3.0.3 on 2021-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=26)),
                ('phonenum', models.CharField(max_length=10, unique=True)),
                ('setdat', models.DateField()),
                ('settime', models.TimeField()),
            ],
        ),
    ]
