# Generated by Django 3.0.3 on 2021-03-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagecut', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('set_date', models.DateField()),
                ('set_time', models.TimeField()),
            ],
        ),
    ]
